"""
The PARAKH brand kit from one geometry: the mark, its animation classes, the lockups, the favicons and the app icons.

    python brand/build_brand.py            text files, then the PNG and ICO files (Playwright with Chrome)
    python brand/build_brand.py --no-png   text files only
    python brand/build_brand.py --check    exit 1 when a text file is out of date (tests/test_brand.py)

The mark sits on a 64-unit grid in three layers (frontend/src/components/brand/parakh.css animates them):
  A  lens     an octagon frame, two lids meeting at its sides, an iris ring
  B  network  three traces from pads on the iris rim that meet at a hub and rise to the beacon
  C  beacon   two chevrons at the top; the lower one cuts a gap into the lids and the iris (a mask)

Writes
  frontend/src/components/brand/parakhMarkup.ts   the animated mark's inner markup for ParakhMark.tsx
  frontend/public/favicon.svg, favicon-alert.svg   the tab icon (the app swaps in the alert one: red beacon)
  frontend/public/manifest.json                   the web app manifest (json: nginx serves it as JSON)
  brand/parakh-logo.js                            <parakh-logo>, a web component with parakh.css inside
  brand/svg/*.svg                                 still marks, animated marks, lockups (light and dark)
  with PNG: frontend/public/favicon.ico, apple-touch-icon.png, icon-192.png, icon-512.png and brand/png/*.png
"""
from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "brand"
PUBLIC = ROOT / "frontend" / "public"
COMPONENT = ROOT / "frontend" / "src" / "components" / "brand"
CSS = COMPONENT / "parakh.css"

# ---- geometry (64 x 64) ---------------------------------------------------------------------------------------------
FRAME = "M20.8 5H43.2L59 20.8V43.2L43.2 59H20.8L5 43.2V20.8Z"
LID_TOP = "M5 32Q32 6 59 32"
LID_BOTTOM = "M5 32Q32 58 59 32"
IRIS = (32, 32, 13)
ROUTES = ("M25 42.95V34L32 27V23", "M32 45V23", "M39 42.95V34L32 27V23")   # left, centre, right: pad to beacon
PADS = ((25, 42.95, 1.8), (39, 42.95, 1.8))
HUB = (32, 27, 1.9)
CHEV_UP = "M25.5 16.5 32 10 38.5 16.5"
CHEV_LO = "M25.5 22.5 32 16 38.5 22.5"
PING = (32, 16, 6)
W = {"frame": 2.2, "lid": 2.4, "iris": 1.8, "trace": 1.9, "chev": 3.8, "knock": 7.2}

# ---- colours --------------------------------------------------------------------------------------------------------
NAVY = "#0e1e3a"
TONES = {
    "light": {"ink": NAVY, "trace": "#1597cc", "beacon": "#f08a24"},
    "dark": {"ink": "#e9eef6", "trace": "#38c6f4", "beacon": "#f5952a"},
}
CRITICAL = "#ff4d5e"
TAGLINE = "INFRASTRUCTURE INTELLIGENCE"
FONT = "'IBM Plex Sans', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"
HEADER = "Generated by brand/build_brand.py; edit the script, not this file."


def _mask(uid: str, blur: bool = False) -> str:
    """The knockout under the lower chevron; with blur also the soft edge of the beacon's halo."""
    # the filter area is the whole canvas: the default (the path's box plus 10 per cent) would clip the blur
    soft = (f'<filter id="pk-soft-{uid}" filterUnits="userSpaceOnUse" x="-8" y="-8" width="80" height="80">'
            f'<feGaussianBlur stdDeviation="1.7"/></filter>') if blur else ""
    return (f'<defs><mask id="pk-knock-{uid}" maskUnits="userSpaceOnUse" x="-8" y="-8" width="80" height="80">'
            f'<rect x="-8" y="-8" width="80" height="80" fill="#fff"/>'
            f'<path d="{CHEV_LO}" fill="none" stroke="#000" stroke-width="{W["knock"]}" stroke-linecap="round" '
            f'stroke-linejoin="round"/></mask>{soft}</defs>')


def animated_inner(uid: str = "__UID__") -> str:
    """The mark with the animation classes of parakh.css; __UID__ keeps the mask id unique per instance."""
    cx, cy, r = IRIS
    px, py, pr = PING
    traces = "".join(f'<path class="pk-trace" pathLength="1" d="{d}"/>' for d in ROUTES)
    pulses = "".join(f'<path class="pk-pulse pk-fx" pathLength="1" d="{d}"/>' for d in ROUTES)
    pads = "".join(f'<circle class="pk-node pk-node--pad" cx="{x}" cy="{y}" r="{rr}"/>' for x, y, rr in PADS)
    hx, hy, hr = HUB
    return (
        _mask(uid, blur=True)
        + '<g class="pk-lens">'
        f'<path class="pk-frame" pathLength="1" d="{FRAME}"/>'
        f'<path class="pk-glint pk-fx" pathLength="1" d="{FRAME}"/>'
        f'<g mask="url(#pk-knock-{uid})">'
        f'<path class="pk-lid" pathLength="1" d="{LID_TOP}"/>'
        f'<path class="pk-lid" pathLength="1" d="{LID_BOTTOM}"/>'
        f'<circle class="pk-iris" pathLength="1" cx="{cx}" cy="{cy}" r="{r}"/></g></g>'
        f'<g class="pk-net">{traces}{pulses}{pads}'
        f'<circle class="pk-node pk-node--hub" cx="{hx}" cy="{hy}" r="{hr}"/></g>'
        '<g class="pk-beacon">'
        f'<circle class="pk-ping pk-fx" cx="{px}" cy="{py}" r="{pr}"/>'
        f'<circle class="pk-ping pk-ping--2 pk-fx" cx="{px}" cy="{py}" r="{pr}"/>'
        f'<g class="pk-lift pk-lift--lo"><path class="pk-glow pk-fx" filter="url(#pk-soft-{uid})" d="{CHEV_LO}"/>'
        f'<path class="pk-chev" d="{CHEV_LO}"/></g>'
        f'<g class="pk-lift pk-lift--up"><path class="pk-glow pk-fx" filter="url(#pk-soft-{uid})" d="{CHEV_UP}"/>'
        f'<path class="pk-chev" d="{CHEV_UP}"/></g></g>'
    )


def still_inner(tone: str, uid: str, beacon: str | None = None) -> str:
    """The still mark with presentation attributes only (no CSS), for files that travel: slides, documents."""
    c = TONES[tone]
    b = beacon or c["beacon"]
    cx, cy, r = IRIS
    line = 'fill="none" stroke-linecap="round" stroke-linejoin="round"'
    nodes = "".join(f'<circle cx="{x}" cy="{y}" r="{rr}"/>' for x, y, rr in (*PADS, HUB))
    return (
        _mask(uid)
        + f'<path d="{FRAME}" {line} stroke="{c["ink"]}" stroke-width="{W["frame"]}"/>'
        f'<g mask="url(#pk-knock-{uid})" {line} stroke="{c["ink"]}">'
        f'<path d="{LID_TOP}" stroke-width="{W["lid"]}"/><path d="{LID_BOTTOM}" stroke-width="{W["lid"]}"/>'
        f'<circle cx="{cx}" cy="{cy}" r="{r}" stroke-width="{W["iris"]}"/></g>'
        f'<path d="{" ".join(ROUTES)}" {line} stroke="{c["trace"]}" stroke-width="{W["trace"]}"/>'
        f'<g fill="{c["trace"]}">{nodes}</g>'
        f'<path d="{CHEV_UP} {CHEV_LO}" {line} stroke="{b}" stroke-width="{W["chev"]}"/>'
    )


def svg_file(inner: str, viewbox: str, width: int, height: int, extra: str = "", title: str = "PARAKH") -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" width="{width}" height="{height}" '
            f'role="img" aria-label="{title}"{extra}><!-- {HEADER} --><title>{title}</title>{inner}</svg>\n')


def still_mark(tone: str) -> str:
    return svg_file(still_inner(tone, "s"), "0 0 64 64", 256, 256)


def animated_mark(tone: str) -> str:
    css = CSS.read_text(encoding="utf-8")
    # CDATA: the file is XML, and the stylesheet's comments hold angle brackets
    return svg_file(f"<style><![CDATA[\n{css}]]></style>{animated_inner('a')}", "0 0 64 64", 256, 256,
                    extra=f' class="pk" data-status="watch" data-tone="{tone}" data-animated="true" '
                          f'data-intro="false"')


def _text(tone: str, x: float, y: float, size: float, length: float, weight: int, anchor: str, body: str,
          opacity: float = 1.0) -> str:
    fill = TONES[tone]["ink"]
    return (f'<text x="{x}" y="{y}" font-family="{FONT}" font-size="{size}" font-weight="{weight}" fill="{fill}" '
            f'fill-opacity="{opacity}" text-anchor="{anchor}" textLength="{length}" lengthAdjust="spacing">'
            f'{body}</text>')


def lockup_horizontal(tone: str) -> str:
    """The mark at the left, PARAKH over the tagline to its right, both lines the same width."""
    inner = (f'<g>{still_inner(tone, "h")}</g>'
             + _text(tone, 78, 37, 31, 150, 700, "start", "PARAKH")
             + _text(tone, 78.6, 52, 7.4, 149, 600, "start", TAGLINE, 0.72))
    return svg_file(inner, "0 0 236 64", 472, 128)


def lockup_stacked(tone: str) -> str:
    """The mark above, PARAKH and the tagline centred under it."""
    inner = (f'<g transform="translate(58 0)">{still_inner(tone, "v")}</g>'
             + _text(tone, 90, 100, 29, 150, 700, "middle", "PARAKH")
             + _text(tone, 90, 116, 7.2, 150, 600, "middle", TAGLINE, 0.72))
    return svg_file(inner, "0 0 180 124", 360, 248)


def favicon(beacon: str) -> str:
    """The tab icon: a navy octagon, a white eye with a cyan pupil and one chevron (the full mark blurs at 16 px)."""
    inner = (f'<path d="M19.6 2.5H44.4L61.5 19.6V44.4L44.4 61.5H19.6L2.5 44.4V19.6Z" fill="{NAVY}" '
             f'stroke="{NAVY}" stroke-width="3" stroke-linejoin="round"/>'
             f'<path d="M11 37Q32 13 53 37Q32 61 11 37Z" fill="none" stroke="#fff" stroke-width="5" '
             f'stroke-linejoin="round"/>'
             f'<circle cx="32" cy="37" r="6.5" fill="#38c6f4"/>'
             f'<path d="M23.5 21 32 12.5 40.5 21" fill="none" stroke="{beacon}" stroke-width="6" '
             f'stroke-linecap="round" stroke-linejoin="round"/>')
    return svg_file(inner, "0 0 64 64", 64, 64)


def app_icon() -> str:
    """The home-screen icon: the dark mark on a full navy square (the platforms round the corners themselves); the
    mark (68 per cent of the width) stays inside the maskable safe circle (80 per cent)."""
    inner = (f'<rect width="64" height="64" fill="{NAVY}"/>'
             f'<g transform="translate(10.24 10.24) scale(0.68)">{still_inner("dark", "i")}</g>')
    return svg_file(inner, "0 0 64 64", 512, 512)


def markup_ts() -> str:
    return (f"// {HEADER}\n"
            "// The PARAKH mark's inner markup (brand/build_brand.py): the classes are parakh.css's, __UID__ keeps the\n"
            "// mask id unique per instance. Static and trusted, so ParakhMark.tsx sets it as HTML.\n"
            "export const PARAKH_VIEWBOX = '0 0 64 64'\n\n"
            f"export const PARAKH_MARKUP =\n  '{animated_inner()}'\n")


def web_component() -> str:
    css = CSS.read_text(encoding="utf-8").replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f"""/* {HEADER}
 * <parakh-logo>: the animated PARAKH mark as a web component, for any page (no framework needed). Load this file
 * with a script element (src="parakh-logo.js"), or paste it into one: it holds no closing script tag. Then
 *   <parakh-logo status="watch" tone="light" size="96"></parakh-logo>
 * Attributes: status stable | watch | critical, tone light | dark, size (px), animated="false" for the still
 * mark, intro to draw it in first, label (the accessible name, default PARAKH). logo.status = 'critical' also works,
 * and logo.replay() plays the intro again. Reduced motion shows the still mark.
 */
(() => {{
  const CSS = `{css}`;
  const MARKUP = '{animated_inner()}';
  const STATUSES = ['stable', 'watch', 'critical'];
  let seq = 0;

  class ParakhLogo extends HTMLElement {{
    static observedAttributes = ['status', 'tone', 'animated', 'intro', 'size', 'label'];

    constructor() {{
      super();
      this.attachShadow({{ mode: 'open' }});
    }}

    connectedCallback() {{
      if (!this.svg) this.render();
    }}

    attributeChangedCallback() {{
      if (this.svg) this.sync();
    }}

    render() {{
      const uid = 'p' + (++seq);
      this.shadowRoot.innerHTML =
        '<style>:host{{display:inline-block;line-height:0}}' + CSS + '</style>' +
        '<svg class="pk" viewBox="0 0 64 64">' + MARKUP.replaceAll('__UID__', uid) + '</svg>';
      this.svg = this.shadowRoot.querySelector('svg');
      this.sync();
    }}

    sync() {{
      const s = this.svg;
      const status = this.getAttribute('status');
      s.dataset.status = STATUSES.includes(status) ? status : 'watch';
      s.dataset.tone = this.getAttribute('tone') === 'dark' ? 'dark' : 'light';
      s.dataset.animated = this.getAttribute('animated') === 'false' ? 'false' : 'true';
      s.dataset.intro = this.hasAttribute('intro') ? 'true' : 'false';
      const size = this.getAttribute('size') || '64';
      s.setAttribute('width', size);
      s.setAttribute('height', size);
      s.setAttribute('role', 'img');
      s.setAttribute('aria-label', this.getAttribute('label') || 'PARAKH');
    }}

    replay() {{
      this.render();
    }}

    get status() {{
      return this.svg ? this.svg.dataset.status : this.getAttribute('status') || 'watch';
    }}

    set status(value) {{
      this.setAttribute('status', value);
    }}
  }}

  if (!customElements.get('parakh-logo')) customElements.define('parakh-logo', ParakhLogo);
}})();
"""


def manifest() -> str:
    return """{
  "name": "PARAKH · Infrastructure Intelligence",
  "short_name": "PARAKH",
  "description": "Early warning for India's central sector infrastructure projects",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#eeeae5",
  "theme_color": "#0e1e3a",
  "icons": [
    { "src": "/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any maskable" },
    { "src": "/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable" }
  ]
}
"""


def text_outputs() -> dict[Path, str]:
    out = {
        COMPONENT / "parakhMarkup.ts": markup_ts(),
        PUBLIC / "favicon.svg": favicon(TONES["light"]["beacon"]),
        PUBLIC / "favicon-alert.svg": favicon(CRITICAL),
        PUBLIC / "manifest.json": manifest(),
        BRAND / "parakh-logo.js": web_component(),
        BRAND / "svg" / "parakh-favicon.svg": favicon(TONES["light"]["beacon"]),
        BRAND / "svg" / "parakh-favicon-alert.svg": favicon(CRITICAL),
        BRAND / "svg" / "parakh-app-icon.svg": app_icon(),
    }
    for tone in ("light", "dark"):
        suffix = "" if tone == "light" else "-dark"
        out[BRAND / "svg" / f"parakh-mark{suffix}.svg"] = still_mark(tone)
        out[BRAND / "svg" / f"parakh-mark-animated{suffix}.svg"] = animated_mark(tone)
        out[BRAND / "svg" / f"parakh-lockup-horizontal{suffix}.svg"] = lockup_horizontal(tone)
        out[BRAND / "svg" / f"parakh-lockup-stacked{suffix}.svg"] = lockup_stacked(tone)
    return out


# ---- raster files (Chrome through Playwright renders the SVGs, with IBM Plex Sans for the lockups) ----------------
FONT_LINK = ('<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@600;700&display=block" '
             'rel="stylesheet">')


def _render(page, svg: str, width: int, height: int, path: Path) -> None:
    body = svg.replace('width="', 'data-w="', 1).replace('height="', 'data-h="', 1)
    page.set_viewport_size({"width": width, "height": height})
    page.set_content(f'<!doctype html><html><head>{FONT_LINK}<style>html,body{{margin:0;background:transparent}}'
                     f'svg{{display:block;width:{width}px;height:{height}px}}</style></head><body>{body}</body></html>')
    page.evaluate("document.fonts.ready.then(() => true)")
    page.wait_for_timeout(150)
    path.parent.mkdir(parents=True, exist_ok=True)
    page.screenshot(path=str(path), omit_background=True, clip={"x": 0, "y": 0, "width": width, "height": height})


def raster_outputs() -> list[Path]:
    from PIL import Image
    from playwright.sync_api import sync_playwright

    fav = favicon(TONES["light"]["beacon"])
    icon = app_icon()
    jobs = [
        (icon, 180, 180, PUBLIC / "apple-touch-icon.png"),
        (icon, 192, 192, PUBLIC / "icon-192.png"),
        (icon, 512, 512, PUBLIC / "icon-512.png"),
        (icon, 512, 512, BRAND / "png" / "parakh-app-icon-512.png"),
        (still_mark("light"), 512, 512, BRAND / "png" / "parakh-mark-512.png"),
        (still_mark("dark"), 512, 512, BRAND / "png" / "parakh-mark-dark-512.png"),
        (lockup_horizontal("light"), 1416, 384, BRAND / "png" / "parakh-lockup-horizontal.png"),
        (lockup_horizontal("dark"), 1416, 384, BRAND / "png" / "parakh-lockup-horizontal-dark.png"),
        (lockup_stacked("light"), 1080, 744, BRAND / "png" / "parakh-lockup-stacked.png"),
        (lockup_stacked("dark"), 1080, 744, BRAND / "png" / "parakh-lockup-stacked-dark.png"),
    ]
    written = []
    with tempfile.TemporaryDirectory() as tmp, sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome")
        page = browser.new_page(device_scale_factor=1)
        for svg, w, h, path in jobs:
            _render(page, svg, w, h, path)
            written.append(path)
        sizes = (16, 32, 48)
        frames = []
        for s in sizes:
            f = Path(tmp) / f"fav-{s}.png"
            _render(page, fav, s, s, f)
            frames.append(Image.open(f).convert("RGBA"))
        browser.close()
        ico = PUBLIC / "favicon.ico"
        frames[-1].save(ico, format="ICO", sizes=[(s, s) for s in sizes], append_images=frames[:-1])
        written.append(ico)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python brand/build_brand.py", description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when a generated text file is out of date")
    ap.add_argument("--no-png", action="store_true", help="skip the PNG and ICO files")
    args = ap.parse_args(argv)

    outputs = text_outputs()
    if args.check:
        stale = [str(p.relative_to(ROOT)) for p, text in outputs.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        for s in stale:
            print(f"out of date: {s}")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    if not args.no_png:
        for path in raster_outputs():
            print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
