import type { Project } from '../contracts/project'
import realProjectsData from './real_projects.json'

/**
 * real_projects.json is generated by pipeline/build_real_projects.py.
 * Re-run that script instead of editing the JSON by hand.
 */
export const MOCK_PROJECTS: Project[] = realProjectsData as Project[]
